name: angulardart_bootstrap
version: 1.0.0
description: AngularDart 5 and Bootstrap 4.3.1
homepage: https://github.com/dart-land/angulardart_bootstrap
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  angular: ^5.2.0
  angular_forms: ^2.1.1
  angular_router: ^2.0.0-alpha+21
  js_shims: ^1.0.0
  intl: ^0.15.0
  bootstrap_scss:
    git: https://github.com/Dart-Land/bootstrap_scss.git
  stream_transform: ^0.0.11
  font_awesome: ^4.7.0
dev_dependencies:
  test: ^1.5.1
  angular_test: ^2.1.0
  build_test: ^0.10.3+3
  build_runner: ^1.1.2
  sass_builder: ^2.1.2


